### ISSUE TITLE
Different behaviour of _ij_reload in 2021.1 and 2021.2

### ISSUE THREAD

**Issue by Pakisan** [Pakisan/jasyncapi-idea-plugin#18]
Research why `_ij_reload=RELOAD_ON_SAVE` has different behaviour in `2021.1`, `2021.2` IDEA

Differences:
- 2021.1 ignores `RELOAD_ON_SAVE` which causes reloading while editing
- 2021.2 respects `RELOAD_ON_SAVE` and reloads on after saving

I think that 2021.1 has different parameter name or knows nothing about it.

References:
- #16

**Comment by philCryoport** [comment]
Hi @Pakisan if work for this issue is still planned, I suggest moving it to https://github.com/asyncapi/jasyncapi-idea-plugin

OTOH if this is completed -- or this issue will _not_ be worked on -- I suggest closing this issue.
