### ISSUE TITLE
Plugin is incompatible with 2021.3 (Build 213.*)

### ISSUE THREAD

**Issue by Harmelodic** [Pakisan/jasyncapi-idea-plugin#24]
As the title states, AsyncAPI plugin is reported as incompatible since the plugin requires 212.* or earlier.

<img width="1094" alt="Screenshot 2021-12-03 at 13 24 44" src="https://user-images.githubusercontent.com/9994373/144602520-5d2bacc8-ecf5-403e-9ba7-f139c904d869.png">

**Comment by Pakisan** [comment]
@Harmelodic hi.

Waiting for review from JetBrains team.

You can wait for a little, or install from disk: 
- release in repo: [1.3.0](https://github.com/Pakisan/jasyncapi-idea-plugin/releases/tag/1.3.0%2Bidea2021)
- release in plugins: [1.3.0](https://plugins.jetbrains.com/plugin/15673-asyncapi/versions/stable/148635)

**Comment by Pakisan** [comment]
@Harmelodic

I close issue because plugin was reviewed and published
