### ISSUE TITLE
Compatibility with IntelliJ IDEA 2022.1 (Build 213.*)

### ISSUE THREAD

**Issue by aalbiach-dkt** [Pakisan/jasyncapi-idea-plugin#29]
AsyncAPI plugin is reported as incompatible with the latest version of IntelliJ IDEA 2022.1 since the plugin requires 213.* build or earlier.

![image](https://user-images.githubusercontent.com/102606506/163154277-25b20bb4-1516-462c-94fd-29ff4d01f2e4.png)

**Comment by Pakisan** [comment]
@aalbiach-dkt working on it. Some issues with tests invocation after update
