### ISSUE TITLE
Suggestions is not working

### ISSUE THREAD

**Issue by aivliev** [Pakisan/jasyncapi-idea-plugin#36]
IntelliJ IDEA 2021.3.3 

Just installed AsyncAPI 1.5.0+idea2021

and suggestions is not working totally for me

Could you please advise on how to fix this? Or trace exact problem

<img width="803" alt="image" src="https://user-images.githubusercontent.com/3439054/165773526-bfdbff8a-7fba-4f45-a2a1-6fc8dc2a8465.png">

Thanks!

**Comment by Pakisan** [comment]
@aivliev hi.

Schema auto completion is not implemented yet. This feature is available only for references - '$ref'.

I think that I will implement it during may. I'm looking for best solution. I Don't want to hard-code completion like swagger plug-in does

**Comment by Pakisan** [comment]
@aivliev hi.

Can you check that everything is working as expected?

https://github.com/Pakisan/jasyncapi-idea-plugin/releases/tag/1.6.0%2Bidea2021

**Comment by aivlievdh** [comment]
Awesome!
it works for 2.3.0 like a charm

Waiting for 2.4.0

Thanks a lot!

I believe for now issues can be closed, waiting general support for 2.4.0


Thanks a lot once again!

**Comment by aivliev** [comment]
﻿Hi  @Pakisan 

Awesome!
it works for 2.3.0 like a charm

Waiting for 2.4.0

Thanks a lot!

I believe for now issues can be closed, waiting general support for 2.4.0


Thanks a lot once again!

**Comment by Pakisan** [comment]
@aivliev glad to hear)

I think that it will be not to hard to implement. Because of using JsonSchema for completion

**Comment by Pakisan** [comment]
@aivliev hi. Auto-completion is available now in 1.6.0 release.

Can you check that everything is working like you expected?

**Comment by aivliev** [comment]
@Pakisan thanks!
just checked - built manually and installed - completion works fine :)
<img width="1056" alt="image" src="https://user-images.githubusercontent.com/3439054/179931642-49e2bcd9-48cf-4dfc-9e98-c7bf339bd0ce.png">


Waiting for publishing of this plugin in idea marketplace

P.S. could you please update README of how to build plugin? looks like first two steps refer to instruction from https://github.com/Pakisan/jasyncapi
I believe it should be
```
git clone https://github.com/Pakisan/jasyncapi-idea-plugin.git
cd jasyncapi-idea-plugin
./gradlew buildPlugin
install plugin from build/libs/
```

But overall looks awesome!
Thanks!

**Comment by aivliev** [comment]
Hm... but looks like like little bit strange
works fine on channels on sample yaml
<img width="1056" alt="image" src="https://user-images.githubusercontent.com/3439054/179932831-daf069b8-72b3-4490-a05b-6d1c233f504a.png">
But not on payload 
<img width="1056" alt="image" src="https://user-images.githubusercontent.com/3439054/179933147-7bafbb4a-3d6a-4566-b9d1-eb6c0704a5a7.png">

Therefore on schemas it is working fine:
<img width="1056" alt="image" src="https://user-images.githubusercontent.com/3439054/179933479-c560bee5-946a-44b0-8988-baf76d2cb169.png">

Is this expected?

**Comment by Pakisan** [comment]
@aivliev hi.

Payload is not described in schema. So I think that is correct behaviour
