### ISSUE TITLE
Compatibility with IntelliJ IDEA 2022.2.* / IU 222.* and later

### ISSUE THREAD

**Issue by aalbiach-dkt** [Pakisan/jasyncapi-idea-plugin#46]
AsyncAPI plugin is reported as incompatible with the latest version of IntelliJ IDEA 2022.2 since the plugin requires 221.* build or earlier.
![image](https://user-images.githubusercontent.com/102606506/181461711-72d8bc19-d2b0-47b5-9caa-4f5f38a7c4df.png)

**Comment by philCryoport** [comment]
@aalbiach-dkt Perhaps rename this "Compatibility with IntelliJ IDEA 2022.2.* / IU 222.* and later"?

**Comment by philCryoport** [comment]
PR: https://github.com/Pakisan/jasyncapi-idea-plugin/pull/47

**Comment by Pakisan** [comment]
I have a plan to review @philCryoport PR and commit AsyncAPI 2.5.0  till end of week

**Comment by Pakisan** [comment]
@cesarbiods @philCryoport @aalbiach-dkt 

1.7.0 - https://github.com/Pakisan/jasyncapi-idea-plugin/releases/tag/1.7.0%2Bidea2021

**Comment by philCryoport** [comment]
> @cesarbiods @philCryoport @aalbiach-dkt
> 
> 1.7.0 - https://github.com/Pakisan/jasyncapi-idea-plugin/releases/tag/1.7.0%2Bidea2021

Hi @Pakisan thank you for pushing that to the marketplace.  I can confirm it previews with no error if I specify v2.4.0 or v2.5.0.

However, I don't see it stating in the preview that indeed this schema is supposed to be compliant to AsyncAPI v2.4.0 or v2.5.0. Am I blind and just missing that?

**Comment by Pakisan** [comment]
@philCryoport 

> However, I don't see it stating in the preview that indeed this schema is supposed to be compliant to AsyncAPI v2.4.0 or v2.5.0. Am I blind and just missing that?

Can you provide more details. I'm a little bit confused because can't understand what's going wrong.

When you working with schema, you declare its version. So plugin retrieves it and searches for relevant JsonSchema to use for validation. If version is unrecognised, file would not be recognised as AsyncAPI schema and would not be registered - no file icon, no validation, no preview buttons

**Comment by philCryoport** [comment]
> @philCryoport
> 
> > However, I don't see it stating in the preview that indeed this schema is supposed to be compliant to AsyncAPI v2.4.0 or v2.5.0. Am I blind and just missing that?
> 
> Can you provide more details. I'm a little bit confused because can't understand what's going wrong.
> 
> When you working with schema, you declare its version. So plugin retrieves it and searches for relevant JsonSchema to use for validation. If version is unrecognised, file would not be recognised as AsyncAPI schema and would not be registered - no file icon, no validation, no preview buttons

Apologies, lemme actually open a new issue.
